---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raid-app
  namespace: argocd-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@
    targetRevision: HEAD
    chart: metrics-server
    helm:
      version: v3
      releaseName: raid-du
      passCredentials: false
      parameters:
        - name: "image.tag"
          value: v0.6.2
      values: |
        defaultArgs:
        - --cert-dir=/tmp
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --kubelet-insecure-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: raid
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
